version: 0.2

phases:
  install:
    runtime-versions:
      docker: latest
    commands:
      - echo "Installing dependencies..."
      - yum update -y
      - yum install -y jq

  pre_build:
    commands:
      - echo "Checking environment variables..."
      - echo "AWS_ACCOUNT_ID = $AWS_ACCOUNT_ID"
      - echo "AWS_DEFAULT_REGION = $AWS_DEFAULT_REGION"
      - echo "IMAGE_REPO_NAME = $IMAGE_REPO_NAME"
      - echo "IMAGE_TAG = $IMAGE_TAG"
      - if [[ -z "$AWS_ACCOUNT_ID" || -z "$AWS_DEFAULT_REGION" || -z "$IMAGE_REPO_NAME" || -z "$IMAGE_TAG" ]]; then echo "Missing required environment variables!" && exit 1; fi
      - echo "Logging in to Amazon ECR..."
      - |
        aws ecr get-login-password --region "$AWS_DEFAULT_REGION" | \
        docker login --username AWS --password-stdin "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com"

  build:
    commands:
      - echo "Starting build phase..."
      - echo "Building Docker image..."
      - docker build -t "$IMAGE_REPO_NAME:$IMAGE_TAG" .
      - docker tag "$IMAGE_REPO_NAME:$IMAGE_TAG" "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG"

  post_build:
    commands:
      - echo "Build completed on $(date)"
      - echo "Pushing the Docker image to ECR..."
      - docker push "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG"
      - echo "Creating imagedefinitions.json file..."
      - |
        echo '{"TaskDefinition":"MyAppTaskDefinitionGreen","ContainerName":"MyAppContainer","ImageURI":"'"$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG"'"}' > imageDetail.json
      - echo "Verifying imagedefinitions.json contents..."
      - cat imagedefinitions.json
      - echo "Listing output files..."
      - ls -lah

artifacts:
  files:
    - imageDetail.json
