version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - yum update -y
      - yum install -y jq

  pre_build:
    commands:
      - echo "Checking environment variables..."
      - echo "AWS_ACCOUNT_ID = $AWS_ACCOUNT_ID"
      - echo "AWS_DEFAULT_REGION = $AWS_DEFAULT_REGION"
      - echo "IMAGE_REPO_NAME = $IMAGE_REPO_NAME"
      - echo "IMAGE_TAG = $IMAGE_TAG"
      - if [[ -z "$AWS_ACCOUNT_ID" || -z "$AWS_DEFAULT_REGION" || -z "$IMAGE_REPO_NAME" || -z "$IMAGE_TAG" ]]; then echo "Missing required environment variables!" && exit 1; fi
      - echo "Logging in to Amazon ECR..."
      - |
        aws ecr get-login-password --region "$AWS_DEFAULT_REGION" | \
        docker login --username AWS --password-stdin "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com"

  build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - echo "Successfully logged in to ECR."

  post_build:
    commands:
      - echo "Build completed on $(date)"
      - echo "Pushing the Docker image to ECR..."
      - docker push "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG"
      - echo "Creating imageDetail.json file..."
      - |
        echo '{
          "TaskDefinition": "MyAppTaskDefinitionBlue",
          "ContainerName": "MyAppContainer",
          "ImageURI": "'"$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG"'"
        }' > imageDetail.json
      - echo "Verifying imageDetail.json contents..."
      - cat imageDetail.json
      - echo "Listing output files..."
      - ls -lah

artifacts:
  files:
    - imageDetail.json
    - appspec.yml
    - task-def-updated.json
